// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbFyEcCajeY4i82RPcS3f1QPrey-Au_zk',
    appId: '1:158020900588:web:d1cdaa4987cf7e407437c9',
    messagingSenderId: '158020900588',
    projectId: 'chatappbackend-9b06e',
    authDomain: 'chatappbackend-9b06e.firebaseapp.com',
    storageBucket: 'chatappbackend-9b06e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv0_x9qf_OOSpQd2eP2QsDJ7vAOyOoptk',
    appId: '1:158020900588:android:48996be938e81ccf7437c9',
    messagingSenderId: '158020900588',
    projectId: 'chatappbackend-9b06e',
    storageBucket: 'chatappbackend-9b06e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvmq6fusmXxzIcgm6Eo6L-2Ua99DZu5q4',
    appId: '1:158020900588:ios:797e2389dd4c8ab47437c9',
    messagingSenderId: '158020900588',
    projectId: 'chatappbackend-9b06e',
    storageBucket: 'chatappbackend-9b06e.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvmq6fusmXxzIcgm6Eo6L-2Ua99DZu5q4',
    appId: '1:158020900588:ios:a2a7a3c5085c9c857437c9',
    messagingSenderId: '158020900588',
    projectId: 'chatappbackend-9b06e',
    storageBucket: 'chatappbackend-9b06e.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
